### ISSUE TITLE
[State of the Art] TLSH

### ISSUE THREAD

**Issue by adulau** [CIRCL/carl-hauser#6]
- [TLSH](https://github.com/trendmicro/tlsh) is missing from the SoA. E.g. TLSH is used in AIL.

**Comment by Vincent-CIRCL** [comment]
Thanks for the feedback. I'm adding TLSH lib and related paper in the SOA.

**Comment by Vincent-CIRCL** [comment]
Added, along with Nilsimsa that was also cited in the TLSH paper and missing from SOA.
Fix commit : https://github.com/CIRCL/carl-hauser/commit/b457e828c69cef3436a451b71eeccc0a08a7aa45
